TARGET = no_aco
CXXFLAGS = -Wall -ansi -O3 

all: ${TARGET}

no_aco: no_aco.cpp Problem.cpp Solution.cpp Timer.C Random.cc Control.cpp util.cpp
	${CXX} ${CXXFLAGS} -o $@ $^

clean:
	@rm -f *~ *.o ${TARGET} core DEADJOE
