#ifndef DEFS_H
#define DEFS_H

// general
#define N_OF_TIMESLOTS 45
//#define PHEROMONE_UPDATE_COEFFICIENT 1000.0 


// defaults
#define DEFAULT_N_OF_ANTS 10
#define DEFAULT_PHEROMONE_EVAPORATION 0.7
//#define DEFAULT_INITIAL_PHEROMONE PHE_MAX
#define DEFAULT_ALPHA 1.0
#define DEFAULT_BETA 0.0
#define DEFAULT_MINIMAL_PHEROMONE 0.1
#define DEFAULT_MAX_STEPS 10000000

#endif DEFS_H